// Herramienta de desarrollo: prueba en tiempo real con teclado de verdad (menú, conducción, pausa).
import puppeteer from 'puppeteer-core';
import path from 'node:path';
import fs from 'node:fs';
const out = process.argv[2] || 'shots';
fs.mkdirSync(out, { recursive: true });
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist', '--mute-audio', '--window-size=1440,810'], defaultViewport: { width: 1440, height: 810 } });
const page = await browser.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push('[pageerror] ' + e.message + '\n' + (e.stack || '')));
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction('window.__game && window.__game.env', { timeout: 60000 });
await page.waitForFunction('!document.getElementById("btn-play").disabled');
const st = () => page.evaluate(() => { const g = window.__game; const p = g.player; return { state: g.state, paused: g.paused, x: +p.pos.x.toFixed(1), z: +p.pos.z.toFixed(1), y: +p.pos.y.toFixed(1), v: +p.v.toFixed(1), q: g.quality, night: g.env.target, audio: g.sfx.ctx ? g.sfx.ctx.state : null, studs: g.save.studs }; });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
console.log('menú', JSON.stringify(await st()));
await page.click('#btn-play');
await wait(600);
console.log('tras Jugar', JSON.stringify(await st()));
await page.keyboard.down('KeyW');
await wait(1500);
await page.keyboard.down('KeyA');
await wait(500);
await page.keyboard.up('KeyA');
await page.keyboard.press('Space');
await wait(300);
console.log('conduciendo', JSON.stringify(await st()));
await page.screenshot({ path: path.join(out, 'l_drive.png') });
await wait(1200);
await page.keyboard.up('KeyW');
await page.keyboard.press('KeyN');
await page.keyboard.press('KeyC');
await page.keyboard.press('KeyV');
await wait(1500);
console.log('N/C/V', JSON.stringify(await st()));
await page.screenshot({ path: path.join(out, 'l_far.png') });
await page.keyboard.press('Escape');
await wait(300);
console.log('pausa', JSON.stringify(await st()));
await page.screenshot({ path: path.join(out, 'l_pause.png') });
await page.click('#p-quality');
await page.click('#p-resume');
await wait(500);
console.log('reanudado', JSON.stringify(await st()));
// Vista móvil
await page.setViewport({ width: 844, height: 390, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
await page.evaluate(() => document.body.classList.add('touch'));
await wait(800);
await page.screenshot({ path: path.join(out, 'l_mobile.png') });
if (errors.length) console.log('\nERRORES:\n' + [...new Set(errors)].slice(0, 20).join('\n'));
else console.log('Sin errores de consola.');
await browser.close();
